# Generated by Django 4.2.5 on 2023-11-13 13:41

import cliente.models
from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('endereco_cliente', models.CharField(max_length=50)),
                ('bairro_cliente', models.CharField(max_length=30)),
                ('cidade_cliente', models.CharField(max_length=30)),
                ('cep_cliente', models.CharField(max_length=9)),
                ('data_nascimento', models.DateField()),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=7)),
                ('primeira_compra', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.CharField(max_length=14)),
                ('nome_produto', models.CharField(max_length=100)),
                ('embalagem', models.CharField(max_length=20)),
                ('tamanho', models.CharField(max_length=20)),
                ('sabor', models.CharField(max_length=10)),
                ('preco_lista', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_vendedor', models.CharField(max_length=14)),
                ('nome_vendedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pedido', models.CharField(max_length=14)),
                ('preco_lista', models.DecimalField(decimal_places=2, max_digits=7, verbose_name=cliente.models.Produto)),
                ('quantidade', models.IntegerField()),
                ('cod_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.produto')),
                ('cod_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.vendedor')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
